

curl -d '{"name":"domain 1", "language": "is"}' -H "Content-Type: application/json" -H "X_Api-key: aVerySecretKey"  -X POST http://localhost:5000/api/v1/domains/1
curl -d '{"name":"community 1", "language": "is"}' -H "Content-Type: application/json" -H "X_Api-key: aVerySecretKey" -X POST http://localhost:5000/api/v1/communities/1
curl -d '{"name":"group 1", "language": "is"}' -H "Content-Type: application/json" -H "X_Api-key: aVerySecretKey" -X POST http://localhost:5000/api/v1/groups/1
curl -d '{"name":"post 1", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 2", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 3", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 4", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 5", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 6", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 7", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 8", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1
curl -d '{"name":"post 9", "description":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}' -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -X POST http://localhost:5000/api/v1/posts/1

sleep 10

curl -d '{ "content":"Ég vil byggja ný gatnamót á mörkum Suðurlandsbrautar og Vegmúla. Þetta er slysahætta og ekki gaman að vera með börn og annað. Þetta verður að laga núna!","group_id":"1", "community_id":"1", "domain_id":"1", "language": "is"}'  -H "X_Api-key: aVerySecretKey" -H "Content-Type: application/json" -H "X_Api-key: O93lFi3GzyjHOTXT" -X POST http://localhost:5000/api/v1/find_similar_posts
